# Dependencies
markdown:         kramdown
highlighter:      rouge
gems:             [jekyll-paginate]

# Permalinks
permalink:        /:title/

# Setup
name:             'A Black Market for the Digital Humanities'
title:            weltliteratur.net
tagline:          'A Black Market for the Digital Humanities'
description:      'A Black Market for the Digital Humanities'
keywords:         digital humanities, weltliteratur, world literature, blog
url:              https://weltliteratur.net
baseurl:          /
base:             https://weltliteratur.net

author:           Frank, Robert & friends

authors:
  robert:
    name: Robert Jäschke
    display_name: Robert
    img: /images/rj.jpg
    email:
    web: https://amor.cms.hu-berlin.de/~jaeschkr/
    orcid: 0000-0003-3271-9653
    twitter:
    github: rjoberon
    description: Professor at Humboldt-Universität zu Berlin.
  mathias:
    name: Mathias Göbel
    display_name: Mathias
    email:
    web: http://mathias-goebel.github.io/
    twitter: goebel_m
    github: mathias-goebel
    img: /images/mg.png
    description: code follows function
  frank:
    name: Frank Fischer
    display_name: Frank
    img: /images/ff.png
    email:
    orcid: 0000-0003-2419-6629
    web: https://lehkost.github.io/
    twitter: umblaetterer
    github: lehkost
    description: Doing Digital Humanities at Freie Universität Berlin.
  christopher:
    name: Christopher Johnson
    display_name: Christopher
    img: /images/cj.jpg
    email:
    orcid: 0000-0002-5832-9429
    web:
    twitter:
    github: christopher-johnson
    description: Researcher for the Göttingen Academy of Sciences.
  peer:
    name: Peer Trilcke
    display_name: Peer
    img: /images/pt.jpg
    email:
    web: https://www.uni-potsdam.de/de/lit-19-jhd/peertrilcke.html
    twitter: peertrilcke
    github: peertrilcke
    description: Professor of Modern German Literature and Media at University of Potsdam.
  ubbo:
    name: Ubbo Veentjer
    display_name: Ubbo
    email:
    web:
    twitter:
    github: ubbo
    description: "Den Code dokumentieren wir später."
  jannik:
    name: Jannik Strötgen
    display_name: Jannik
    email:
    web: https://sites.google.com/view/jannikstroetgen/
    twitter: jannikstroetgen
    github: JannikStroetgen
    description: Professor at the University of Applied Sciences Karlsruhe.
  angelika:
    name: Angelika Hechtl
    display_name: Angelika
    img: /images/ah.jpg
    email:
    web: http://www.likeanga.at/
    twitter: angelikah
    github: likeanga
    orcid: 0000-0001-6104-7484
    description: Doing Linguistics and Digital Humanities at WU Wien.
  ingo:
    name: Ingo Börner
    display_name: Ingo
    img: /images/ib.jpg
    email:
    web:
    twitter: ingoboerner
    github: ingoboerner
    orcid: 0000-0001-8294-2541
    description: Doing Digital Humanities at University of Potsdam.
  galina:
    name: Galina Ryazanskaya
    display_name: Galina
    img: /images/gr.jpg
    email:
    web:
    twitter:
    github:
    description: University of Potsdam.
  alena:
    name: Alena Shchevyeva
    display_name: Alena
    email:
    web:
    twitter:
    github:
    description: Formerly HSE, Moscow.
  maria:
    name: Maria Suvorova
    display_name: Maria
    email:
    web:
    twitter:
    github: brouhahaha
    description: Formerly HSE, Moscow.
  eduard:
    name: Eduard Grigoryev
    display_name: Eduard
    img: /images/eg.jpg
    email:
    web:
    twitter:
    github: ldsad7
    orcid:
    description: Formerly HSE, Moscow.
  laure:
    name: Laure Barbot
    display_name: Laure
    img: /images/lb.jpg
    email:
    web: https://cmb.hu-berlin.de/en/team/profil/laure-barbot/
    twitter:
    github:
    orcid: 0000-0002-6008-7959
    description: Project officer at DARIAH-EU, Berlin.
  yoann:
    name: Yoann Moranville
    display_name: Yoann
    email:
    web:
    twitter:
    github: yoannspace
    orcid: 0000-0002-3502-1667
    description: Developer at DARIAH. Technical Coordinator of OPERAS.
  ivan:
    name: Ivan Pozdniakov
    display_name: Ivan
    email:
    web:
    twitter: pozdniakov_is
    github: Pozdniakov
    orcid:
    description: Formerly HSE, Moscow.
  michel:
    name: Michel Schwab
    display_name: Michel
    email:
    web: https://amor.cms.hu-berlin.de/~schwabmi/
    orcid:
    twitter:
    description: Research fellow at Humboldt University of Berlin.
  cmil:
    name: Carsten Milling
    display_name: Carsten
    img: /images/cmil.jpg
    email:
    web:
    github: cmil
    orcid:
    twitter:
    description: DraCor Technical Lead.
  mark:
    name: Mark Schwindt
    display_name: Mark
    img: /images/ms.jpg
    email:
    web: https://www.markschwindt.com/
    github: markschwindt
    orcid: 0000-0002-4337-2467
    twitter: MarkSchwindtFD
    description: DraCor Art Director.
  lisa:
    name: Lisa Poggel
    display_name: Lisa
    img: /images/lp.png
    email:
    web:
    github: lipogg
    orcid: 0000-0003-1051-8148
    twitter:
    description: Digital historian in training at Freie Universität Berlin.
  jonah:
    name: Jonah Lubin
    display_name: Jonah
    img: /images/jl.jpg
    email:
    web: https://www.jonahlubin.net/
    github:
    orcid:
    twitter:
    description: Yiddish and digital humanities at the FU Berlin.

paginate:         10

# Custom vars
version:          0.0.1
# disqus:
github:
repo:             https://github.com/weltliteratur
